// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: armory.sql

package database

import (
	"context"
	"database/sql"
	"strings"
)

const clearAllWeaponStats = `-- name: ClearAllWeaponStats :exec
DELETE FROM weapon_stats
`

func (q *Queries) ClearAllWeaponStats(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearAllWeaponStats)
	return err
}

const clearAllWeaponsData = `-- name: ClearAllWeaponsData :exec
DELETE FROM weapons
`

func (q *Queries) ClearAllWeaponsData(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearAllWeaponsData)
	return err
}

const clearAllWeaponsPerks = `-- name: ClearAllWeaponsPerks :exec
DELETE FROM weapon_perks
`

func (q *Queries) ClearAllWeaponsPerks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearAllWeaponsPerks)
	return err
}

const clearWeaponPerks = `-- name: ClearWeaponPerks :exec
DELETE FROM weapon_perks WHERE instance_id = ?
`

func (q *Queries) ClearWeaponPerks(ctx context.Context, instanceID string) error {
	_, err := q.db.ExecContext(ctx, clearWeaponPerks, instanceID)
	return err
}

const clearWeaponStats = `-- name: ClearWeaponStats :exec
DELETE FROM weapon_stats WHERE instance_id = ?
`

func (q *Queries) ClearWeaponStats(ctx context.Context, instanceID string) error {
	_, err := q.db.ExecContext(ctx, clearWeaponStats, instanceID)
	return err
}

const getAllCharacters = `-- name: GetAllCharacters :many
SELECT character_id, class_type, light_level, emblem_url, last_played, emblem_background_path, title_record_hash, emblem_color_r, emblem_color_g, emblem_color_b, emblem_color_a FROM characters
ORDER BY last_played DESC
`

func (q *Queries) GetAllCharacters(ctx context.Context) ([]Character, error) {
	rows, err := q.db.QueryContext(ctx, getAllCharacters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.CharacterID,
			&i.ClassType,
			&i.LightLevel,
			&i.EmblemUrl,
			&i.LastPlayed,
			&i.EmblemBackgroundPath,
			&i.TitleRecordHash,
			&i.EmblemColorR,
			&i.EmblemColorG,
			&i.EmblemColorB,
			&i.EmblemColorA,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllWeapons = `-- name: GetAllWeapons :many
SELECT instance_id, hash, name, type, power, kills, level, location, updated_at, tier, icon_url, slot, damage_type, ammo_type, character_id FROM weapons
`

func (q *Queries) GetAllWeapons(ctx context.Context) ([]Weapon, error) {
	rows, err := q.db.QueryContext(ctx, getAllWeapons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Weapon
	for rows.Next() {
		var i Weapon
		if err := rows.Scan(
			&i.InstanceID,
			&i.Hash,
			&i.Name,
			&i.Type,
			&i.Power,
			&i.Kills,
			&i.Level,
			&i.Location,
			&i.UpdatedAt,
			&i.Tier,
			&i.IconUrl,
			&i.Slot,
			&i.DamageType,
			&i.AmmoType,
			&i.CharacterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllWeaponsWithPerks = `-- name: GetAllWeaponsWithPerks :many
SELECT w.instance_id, w.hash, w.name, w.type, w.power, w.kills, w.level, w.location, w.updated_at, w.tier, w.icon_url, w.slot, w.damage_type, w.ammo_type, w.character_id, 
       GROUP_CONCAT(p.perk_name, ',') as perks_list
FROM weapons w
LEFT JOIN weapon_perks p ON w.instance_id = p.instance_id
GROUP BY w.instance_id
`

type GetAllWeaponsWithPerksRow struct {
	InstanceID  string         `json:"instance_id"`
	Hash        int64          `json:"hash"`
	Name        string         `json:"name"`
	Type        string         `json:"type"`
	Power       int64          `json:"power"`
	Kills       int64          `json:"kills"`
	Level       int64          `json:"level"`
	Location    string         `json:"location"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	Tier        sql.NullString `json:"tier"`
	IconUrl     sql.NullString `json:"icon_url"`
	Slot        sql.NullString `json:"slot"`
	DamageType  sql.NullString `json:"damage_type"`
	AmmoType    sql.NullInt64  `json:"ammo_type"`
	CharacterID sql.NullString `json:"character_id"`
	PerksList   string         `json:"perks_list"`
}

func (q *Queries) GetAllWeaponsWithPerks(ctx context.Context) ([]GetAllWeaponsWithPerksRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllWeaponsWithPerks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllWeaponsWithPerksRow
	for rows.Next() {
		var i GetAllWeaponsWithPerksRow
		if err := rows.Scan(
			&i.InstanceID,
			&i.Hash,
			&i.Name,
			&i.Type,
			&i.Power,
			&i.Kills,
			&i.Level,
			&i.Location,
			&i.UpdatedAt,
			&i.Tier,
			&i.IconUrl,
			&i.Slot,
			&i.DamageType,
			&i.AmmoType,
			&i.CharacterID,
			&i.PerksList,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCharactersWithStats = `-- name: GetCharactersWithStats :many
SELECT 
    c.character_id, 
    c.class_type, 
    c.light_level, 
    c.emblem_url, 
    c.last_played,
    c.emblem_background_path,
    c.title_record_hash,
    c.emblem_color_r,
    c.emblem_color_g,
    c.emblem_color_b,
    c.emblem_color_a,
    s.stat_hash,
    s.value as stat_value
FROM characters c
LEFT JOIN character_stats s ON c.character_id = s.character_id
ORDER BY c.last_played DESC
`

type GetCharactersWithStatsRow struct {
	CharacterID          string         `json:"character_id"`
	ClassType            int64          `json:"class_type"`
	LightLevel           int64          `json:"light_level"`
	EmblemUrl            sql.NullString `json:"emblem_url"`
	LastPlayed           sql.NullTime   `json:"last_played"`
	EmblemBackgroundPath sql.NullString `json:"emblem_background_path"`
	TitleRecordHash      interface{}    `json:"title_record_hash"`
	EmblemColorR         sql.NullInt64  `json:"emblem_color_r"`
	EmblemColorG         sql.NullInt64  `json:"emblem_color_g"`
	EmblemColorB         sql.NullInt64  `json:"emblem_color_b"`
	EmblemColorA         sql.NullInt64  `json:"emblem_color_a"`
	StatHash             interface{}    `json:"stat_hash"`
	StatValue            sql.NullInt64  `json:"stat_value"`
}

func (q *Queries) GetCharactersWithStats(ctx context.Context) ([]GetCharactersWithStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getCharactersWithStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCharactersWithStatsRow
	for rows.Next() {
		var i GetCharactersWithStatsRow
		if err := rows.Scan(
			&i.CharacterID,
			&i.ClassType,
			&i.LightLevel,
			&i.EmblemUrl,
			&i.LastPlayed,
			&i.EmblemBackgroundPath,
			&i.TitleRecordHash,
			&i.EmblemColorR,
			&i.EmblemColorG,
			&i.EmblemColorB,
			&i.EmblemColorA,
			&i.StatHash,
			&i.StatValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDuplicatesByHash = `-- name: GetDuplicatesByHash :many
SELECT instance_id, hash, name, type, power, kills, level, location, updated_at, tier, icon_url, slot, damage_type, ammo_type, character_id FROM weapons 
WHERE hash = ?
ORDER BY power DESC
`

func (q *Queries) GetDuplicatesByHash(ctx context.Context, hash int64) ([]Weapon, error) {
	rows, err := q.db.QueryContext(ctx, getDuplicatesByHash, hash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Weapon
	for rows.Next() {
		var i Weapon
		if err := rows.Scan(
			&i.InstanceID,
			&i.Hash,
			&i.Name,
			&i.Type,
			&i.Power,
			&i.Kills,
			&i.Level,
			&i.Location,
			&i.UpdatedAt,
			&i.Tier,
			&i.IconUrl,
			&i.Slot,
			&i.DamageType,
			&i.AmmoType,
			&i.CharacterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGodRollCandidates = `-- name: GetGodRollCandidates :many
SELECT 
  w.instance_id, w.hash, w.name, w.type, w.power, w.kills, w.level, w.location, w.updated_at, w.tier, w.icon_url, w.slot, w.damage_type, w.ammo_type, w.character_id FROM weapons w
JOIN weapon_perks p ON w.instance_id = p.instance_id
JOIN weapon_stats s ON w.instance_id = s.instance_id
WHERE p.perk_name = ? AND s.stat_name = 'Range' AND s.value > ?
`

type GetGodRollCandidatesParams struct {
	PerkName string `json:"perk_name"`
	Value    int64  `json:"value"`
}

func (q *Queries) GetGodRollCandidates(ctx context.Context, arg GetGodRollCandidatesParams) ([]Weapon, error) {
	rows, err := q.db.QueryContext(ctx, getGodRollCandidates, arg.PerkName, arg.Value)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Weapon
	for rows.Next() {
		var i Weapon
		if err := rows.Scan(
			&i.InstanceID,
			&i.Hash,
			&i.Name,
			&i.Type,
			&i.Power,
			&i.Kills,
			&i.Level,
			&i.Location,
			&i.UpdatedAt,
			&i.Tier,
			&i.IconUrl,
			&i.Slot,
			&i.DamageType,
			&i.AmmoType,
			&i.CharacterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWeaponComparison = `-- name: GetWeaponComparison :many
SELECT instance_id, hash, name, type, power, kills, level, location, updated_at, tier, icon_url, slot, damage_type, ammo_type, character_id FROM weapons 
WHERE instance_id IN (/*SLICE:instance_ids*/?)
ORDER BY power DESC
`

func (q *Queries) GetWeaponComparison(ctx context.Context, instanceIds []string) ([]Weapon, error) {
	query := getWeaponComparison
	var queryParams []interface{}
	if len(instanceIds) > 0 {
		for _, v := range instanceIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:instance_ids*/?", strings.Repeat(",?", len(instanceIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:instance_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Weapon
	for rows.Next() {
		var i Weapon
		if err := rows.Scan(
			&i.InstanceID,
			&i.Hash,
			&i.Name,
			&i.Type,
			&i.Power,
			&i.Kills,
			&i.Level,
			&i.Location,
			&i.UpdatedAt,
			&i.Tier,
			&i.IconUrl,
			&i.Slot,
			&i.DamageType,
			&i.AmmoType,
			&i.CharacterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWeaponsByLocation = `-- name: GetWeaponsByLocation :many
SELECT instance_id, hash, name, type, power, kills, level, location, updated_at, tier, icon_url, slot, damage_type, ammo_type, character_id FROM weapons 
WHERE location = ?
ORDER BY name ASC
`

func (q *Queries) GetWeaponsByLocation(ctx context.Context, location string) ([]Weapon, error) {
	rows, err := q.db.QueryContext(ctx, getWeaponsByLocation, location)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Weapon
	for rows.Next() {
		var i Weapon
		if err := rows.Scan(
			&i.InstanceID,
			&i.Hash,
			&i.Name,
			&i.Type,
			&i.Power,
			&i.Kills,
			&i.Level,
			&i.Location,
			&i.UpdatedAt,
			&i.Tier,
			&i.IconUrl,
			&i.Slot,
			&i.DamageType,
			&i.AmmoType,
			&i.CharacterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWeaponsByName = `-- name: GetWeaponsByName :many
SELECT instance_id, hash, name, type, power, kills, level, location, updated_at, tier, icon_url, slot, damage_type, ammo_type, character_id FROM weapons 
WHERE name LIKE ?
ORDER BY power DESC
`

func (q *Queries) GetWeaponsByName(ctx context.Context, name string) ([]Weapon, error) {
	rows, err := q.db.QueryContext(ctx, getWeaponsByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Weapon
	for rows.Next() {
		var i Weapon
		if err := rows.Scan(
			&i.InstanceID,
			&i.Hash,
			&i.Name,
			&i.Type,
			&i.Power,
			&i.Kills,
			&i.Level,
			&i.Location,
			&i.UpdatedAt,
			&i.Tier,
			&i.IconUrl,
			&i.Slot,
			&i.DamageType,
			&i.AmmoType,
			&i.CharacterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWeaponsByType = `-- name: GetWeaponsByType :many
SELECT instance_id, hash, name, type, power, kills, level, location, updated_at, tier, icon_url, slot, damage_type, ammo_type, character_id FROM weapons 
WHERE type = ?
ORDER BY power DESC, name ASC
`

func (q *Queries) GetWeaponsByType(ctx context.Context, type_ string) ([]Weapon, error) {
	rows, err := q.db.QueryContext(ctx, getWeaponsByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Weapon
	for rows.Next() {
		var i Weapon
		if err := rows.Scan(
			&i.InstanceID,
			&i.Hash,
			&i.Name,
			&i.Type,
			&i.Power,
			&i.Kills,
			&i.Level,
			&i.Location,
			&i.UpdatedAt,
			&i.Tier,
			&i.IconUrl,
			&i.Slot,
			&i.DamageType,
			&i.AmmoType,
			&i.CharacterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertWeaponPerk = `-- name: InsertWeaponPerk :exec
INSERT INTO weapon_perks (instance_id, perk_hash, perk_name, is_equipped, socket_index)
VALUES (?, ?, ?, ?, ?)
`

type InsertWeaponPerkParams struct {
	InstanceID  string `json:"instance_id"`
	PerkHash    int64  `json:"perk_hash"`
	PerkName    string `json:"perk_name"`
	IsEquipped  bool   `json:"is_equipped"`
	SocketIndex int64  `json:"socket_index"`
}

func (q *Queries) InsertWeaponPerk(ctx context.Context, arg InsertWeaponPerkParams) error {
	_, err := q.db.ExecContext(ctx, insertWeaponPerk,
		arg.InstanceID,
		arg.PerkHash,
		arg.PerkName,
		arg.IsEquipped,
		arg.SocketIndex,
	)
	return err
}

const insertWeaponStat = `-- name: InsertWeaponStat :exec
INSERT INTO 
  weapon_stats (instance_id, stat_name, value) VALUES (?, ?, ?)
`

type InsertWeaponStatParams struct {
	InstanceID string `json:"instance_id"`
	StatName   string `json:"stat_name"`
	Value      int64  `json:"value"`
}

func (q *Queries) InsertWeaponStat(ctx context.Context, arg InsertWeaponStatParams) error {
	_, err := q.db.ExecContext(ctx, insertWeaponStat, arg.InstanceID, arg.StatName, arg.Value)
	return err
}

const searchWeaponsByPattern = `-- name: SearchWeaponsByPattern :many
SELECT instance_id, hash, name, type, power, kills, level, location, updated_at, tier, icon_url, slot, damage_type, ammo_type, character_id FROM weapons 
WHERE name LIKE ?
ORDER BY power DESC
`

func (q *Queries) SearchWeaponsByPattern(ctx context.Context, name string) ([]Weapon, error) {
	rows, err := q.db.QueryContext(ctx, searchWeaponsByPattern, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Weapon
	for rows.Next() {
		var i Weapon
		if err := rows.Scan(
			&i.InstanceID,
			&i.Hash,
			&i.Name,
			&i.Type,
			&i.Power,
			&i.Kills,
			&i.Level,
			&i.Location,
			&i.UpdatedAt,
			&i.Tier,
			&i.IconUrl,
			&i.Slot,
			&i.DamageType,
			&i.AmmoType,
			&i.CharacterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCharacter = `-- name: UpsertCharacter :exec
INSERT INTO characters (
    character_id, 
    class_type, 
    light_level, 
    emblem_url, 
    last_played,
    emblem_background_path,
    title_record_hash,
    emblem_color_r,
    emblem_color_g,
    emblem_color_b,
    emblem_color_a
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(character_id) DO UPDATE SET
    light_level = excluded.light_level,
    last_played = excluded.last_played,
    emblem_url = excluded.emblem_url,
    emblem_background_path = excluded.emblem_background_path,
    title_record_hash = excluded.title_record_hash,
    emblem_color_r = excluded.emblem_color_r,
    emblem_color_g = excluded.emblem_color_g,
    emblem_color_b = excluded.emblem_color_b,
    emblem_color_a = excluded.emblem_color_a
`

type UpsertCharacterParams struct {
	CharacterID          string         `json:"character_id"`
	ClassType            int64          `json:"class_type"`
	LightLevel           int64          `json:"light_level"`
	EmblemUrl            sql.NullString `json:"emblem_url"`
	LastPlayed           sql.NullTime   `json:"last_played"`
	EmblemBackgroundPath sql.NullString `json:"emblem_background_path"`
	TitleRecordHash      interface{}    `json:"title_record_hash"`
	EmblemColorR         sql.NullInt64  `json:"emblem_color_r"`
	EmblemColorG         sql.NullInt64  `json:"emblem_color_g"`
	EmblemColorB         sql.NullInt64  `json:"emblem_color_b"`
	EmblemColorA         sql.NullInt64  `json:"emblem_color_a"`
}

func (q *Queries) UpsertCharacter(ctx context.Context, arg UpsertCharacterParams) error {
	_, err := q.db.ExecContext(ctx, upsertCharacter,
		arg.CharacterID,
		arg.ClassType,
		arg.LightLevel,
		arg.EmblemUrl,
		arg.LastPlayed,
		arg.EmblemBackgroundPath,
		arg.TitleRecordHash,
		arg.EmblemColorR,
		arg.EmblemColorG,
		arg.EmblemColorB,
		arg.EmblemColorA,
	)
	return err
}

const upsertCharacterStat = `-- name: UpsertCharacterStat :exec
INSERT INTO character_stats (character_id, stat_hash, value)
VALUES (?, ?, ?)
ON CONFLICT(character_id, stat_hash) DO UPDATE SET
    value = excluded.value
`

type UpsertCharacterStatParams struct {
	CharacterID string      `json:"character_id"`
	StatHash    interface{} `json:"stat_hash"`
	Value       int64       `json:"value"`
}

func (q *Queries) UpsertCharacterStat(ctx context.Context, arg UpsertCharacterStatParams) error {
	_, err := q.db.ExecContext(ctx, upsertCharacterStat, arg.CharacterID, arg.StatHash, arg.Value)
	return err
}

const upsertWeapon = `-- name: UpsertWeapon :exec
INSERT INTO weapons (
    instance_id, hash, name, type, power, kills, level, location, 
    tier, icon_url, slot, damage_type, ammo_type, character_id
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(instance_id) DO UPDATE SET
    power = excluded.power,
    kills = excluded.kills,
    level = excluded.level,
    location = excluded.location,
    character_id = excluded.character_id
`

type UpsertWeaponParams struct {
	InstanceID  string         `json:"instance_id"`
	Hash        int64          `json:"hash"`
	Name        string         `json:"name"`
	Type        string         `json:"type"`
	Power       int64          `json:"power"`
	Kills       int64          `json:"kills"`
	Level       int64          `json:"level"`
	Location    string         `json:"location"`
	Tier        sql.NullString `json:"tier"`
	IconUrl     sql.NullString `json:"icon_url"`
	Slot        sql.NullString `json:"slot"`
	DamageType  sql.NullString `json:"damage_type"`
	AmmoType    sql.NullInt64  `json:"ammo_type"`
	CharacterID sql.NullString `json:"character_id"`
}

func (q *Queries) UpsertWeapon(ctx context.Context, arg UpsertWeaponParams) error {
	_, err := q.db.ExecContext(ctx, upsertWeapon,
		arg.InstanceID,
		arg.Hash,
		arg.Name,
		arg.Type,
		arg.Power,
		arg.Kills,
		arg.Level,
		arg.Location,
		arg.Tier,
		arg.IconUrl,
		arg.Slot,
		arg.DamageType,
		arg.AmmoType,
		arg.CharacterID,
	)
	return err
}
