// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"time"
)

const getUser = `-- name: GetUser :one
SELECT membership_id, display_name, access_token, refresh_token, expires_in, refresh_expires_in, received_at, created_at, updated_at FROM users
WHERE membership_id = ? LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, membershipID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, membershipID)
	var i User
	err := row.Scan(
		&i.MembershipID,
		&i.DisplayName,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresIn,
		&i.RefreshExpiresIn,
		&i.ReceivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO users (
    membership_id, display_name, access_token, refresh_token, 
    expires_in, refresh_expires_in, received_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(membership_id) DO UPDATE SET
    access_token = excluded.access_token,
    refresh_token = excluded.refresh_token,
    expires_in = excluded.expires_in,
    refresh_expires_in = excluded.refresh_expires_in,
    received_at = excluded.received_at,
    updated_at = excluded.updated_at
`

type UpsertUserParams struct {
	MembershipID     string    `json:"membership_id"`
	DisplayName      string    `json:"display_name"`
	AccessToken      string    `json:"access_token"`
	RefreshToken     string    `json:"refresh_token"`
	ExpiresIn        int64     `json:"expires_in"`
	RefreshExpiresIn int64     `json:"refresh_expires_in"`
	ReceivedAt       time.Time `json:"received_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.ExecContext(ctx, upsertUser,
		arg.MembershipID,
		arg.DisplayName,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresIn,
		arg.RefreshExpiresIn,
		arg.ReceivedAt,
		arg.UpdatedAt,
	)
	return err
}
